#ifndef _SYSCALL_NB_COMMON_H_
#define _SYSCALL_NB_COMMON_H_

typedef enum
{
    SYSCALL_GETC = 0,
    SYSCALL_EXEC = 1,
    SYSCALL_SET_CUSRSOR = 2,
    SYSCALL_PUTS = 3,
    SYSCALL_FILE_STAT = 4,
    SYSCALL_FILE_READ = 5,
    SYSCALL_READ_STRING = 6,
    SYSCALL_SLEEP = 7,
    SYSCALL_RANDOM = 8,
    SYSCALL_PUTS_X_Y = 9,
    SYSCALL_CLEAN_X_Y = 10,
    SYSCALL_LS = 11,
    SYSCALL_ENABLE_CURSOR = 12,
    SYSCALL_DISABLE_CURSOR = 13,
    __SYSCALL_END__
} syscall_t;

#endif
